# Generated by Django 5.2 on 2025-05-04 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contact', '0003_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_intent_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
